### PR TITLE
README: use SVG, remove duplicate RST

### PR DESCRIPTION
**Pull request by hugovk**
Two changes:

---

1. Use SVG badges for consistency:

Before:

image

https://github.com/davedoesdev/python-jwt/blob/49d0987a750b08569960d61d71f5137c7657919b/README.md

After:

image

https://github.com/davedoesdev/python-jwt/blob/61b3992112141be83f86283e680d5f314563a03e/README.md

---

2. Remove duplicate README.rst 

The good news is the new PyPI (aka Warehouse) now supports Markdown for the description, so we can use README.md without conversion!

For more info and examples:
* https://pypi.org/project/markdown-description-example/
* https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
* https://github.com/di/markdown-description-example

### CODE REVIEW

**Comment by davedoesdev** [comment]
Thanks @hugovk appreciate it!

**Comment by hugovk** [comment]
How 3 welcome! Markdown on PyPI is really welcome!

**Comment by davedoesdev** [comment]
Yes it is indeed. I'd prefer AsciiDoc though!

**Comment by davedoesdev** [comment]
@hugovk pypi doesn't seem to be formatting the markdown for me: https://pypi.org/project/python_jwt/

**Comment by davedoesdev** [comment]
Possibly I need to upgrade wheel: https://github.com/pypa/warehouse/issues/3664

**Comment by davedoesdev** [comment]
:( No joy

**Comment by davedoesdev** [comment]
OK looks like I fixed it by upgrading setuptools, wheel and twine and using python 3.
Python packaging still as good as ever.

**Comment by hugovk** [comment]
Yes, I should have made it clearer, it needs setuptools>=38.6.0, wheel>=0.31.0 and twine>=1.11.0.

https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

https://pypi.org/project/python_jwt/ looks good now!

**Pull request merged**
